version: '3.8'
services:
  basic-mysql:
    container_name: basic-mysql
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=testing
      - MYSQL_ROOT_PASSWORD=ANSKk08aPEDbFjDO
    ports:
      - '3306:3306'
      - '33060:33060'
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - basic-mysql:/var/lib/mysql
      - ./basic-mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  basic-mysql:
    driver: local